### ISSUE TITLE
Copyright page name in NCX and HTML toc

### ISSUE THREAD

**Issue by chrxr** [andrgosl/PUK_XProc_Dev#35]
Currently it's picking up the heading name PENGUIN SHORTS, should be "Copyright"

**Comment by nic-gibson** [comment]
Do you mean that it's picking up the heading "PENGUIN BOOKS"? There is no "PENGUIN SHORTS" heading. If so, that's because the title says PENGUIN BOOKS. Change the title and you'll get it!

## nic

Corbas Consulting / @CorbasLtd
Digital Publishing Consultancy and Training
http://www.corbas.co.uk, +44 (0)7718 906817/+44 (0)1273 930765

**Comment by chrxr** [comment]
I thought that might be the answer... I'll get back to you.

Date: Thu, 20 Sep 2012 07:38:02 -0700
